build.sh, package.json, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/sass/global/_competences-specifics.scss, src/main/resources/public/sass/global/sniplets/_memento-notes.scss, src/main/resources/public/template/behaviours/sniplet-notes-memento-widget.html, src/main/resources/public/ts/behaviours.ts, src/main/resources/public/ts/models/common/Periode.ts, src/main/resources/public/ts/models/teacher/CompetenceNote.ts, src/main/resources/public/ts/models/teacher/Devoir.ts, src/main/resources/public/ts/models/teacher/Evaluation.ts, src/main/resources/public/ts/models/teacher/Matiere.ts, src/main/resources/public/ts/services/devoirs.service.ts, src/main/resources/public/ts/services/periods.service.ts, src/main/resources/public/ts/sniplets/memento/index.ts, src/main/resources/public/ts/sniplets/memento/notes.ts, src/main/resources/public/ts/teachers.ts, src/main/resources/public/ts/utils/date.ts
Check
https://github.com/OPEN-ENT-NG/vie-scolaire/pull/14
https://github.com/OPEN-ENT-NG/presences/pull/54
Vue Global
Vue dernière note (version maquette)
Vue moyenne des matières (version maquette)
Vue détaille des notes d'une matière (version maquette)
=> feat(sniplet): #EVAL-255 add sniplet displaying notes in memento

src/main/resources/public/ts/sniplets/memento/notes.ts
Bug due to the non-reinitialization of several variables
=> fix(memento): #EVAL-271 bad display when reopening a memento

src/main/resources/public/template/pdf/releve-eleve.pdf.xhtml
... of data displayed on the page before it.
=> fix(ReleveNote): EVAL-284 Fixed last page could be blank on certain amounts... 

src/main/java/fr/openent/competences/service/impl/DefaultBilanPerioqueService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
Modification de l'appel d'api pour les raisons et les évènements. (Évolution PR https://github.com/OPEN-ENT-NG/presences/pull/83, https://entconf.gdapublic.fr/display/MP/Event, https://entconf.gdapublic.fr/pages/viewpage.action?pageId=36707774, https://entconf.gdapublic.fr/pages/viewpage.action?pageId=72516976)
=> fix(bulletin): #EVAL-317 fix lateness do not go up in a bulletin

src/main/resources/i18n/fr.json, src/main/resources/public/sass/global/specifics/_competences.scss, src/main/resources/public/template/directives/cSkillsList.html, src/main/resources/public/template/enseignants/creation_competence/lightbox_creation_competence.html, src/main/resources/public/template/enseignants/creation_devoir/display_creation_devoir.html, src/main/resources/public/template/enseignants/creation_devoir/lightbox_competences_domaines.html, src/main/resources/public/template/personnels/param_items/lightbox_competences_domaines.html, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/directives/cSkillsList.ts
…ce while making an evaluation.
=> feat(Evaluation): EVAL-140 Added a lightbox to create a competen…   

LICENCE, README.md
ajout de la nouvelle licence et de la description technique
merge seulement après vérification de la doc technique par les PO
=> docs: #CO-1626 add new licence and technical description

src/main/resources/public/ts/directives/ProportionSuiviCompetence.ts, src/main/resources/public/ts/utils/functions/initChartsEval.ts
Fixed enseignement view which counted a competence note multiple times in case it was linked to multiple domains
https://entsupport.gdapublic.fr/browse/EVAL-219
=> fix(SuiviEleve): EVAL-219 Fixed enseignement view which counted a competence note multiple times in case it was linked to multiple domains.

src/main/resources/public/template/enseignants/liste_devoirs/display_devoirs_structure.html, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
Fix a bug, when closing the lightbox, the state of the checkboxes were incorrectly reset
EVAL-327 : https://entsupport.gdapublic.fr/browse/EVAL-327
=> fix(duplicationDevoir): EVAL-327  check lightbox Error

gulpfile.js, package.json, src/main/resources/public/sass/global/_competences-specifics.scss, src/main/resources/public/sass/global/sniplets/_services.scss, src/main/resources/public/sass/global/specifics/_materialize.scss, src/main/resources/public/template/behaviours/sniplet-paramServices.html
Ajout d'un icone lors de la présence d une sous matière
https://entsupport.gdapublic.fr/browse/EVAL-329
=> Eval 329/new icon services

src/main/java/fr/openent/competences/service/impl/DefaultExportService.java, src/main/resources/public/template/pdf/releve-eleve.pdf.xhtml, src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts, src/main/resources/public/ts/utils/functions/average.ts
=> Eval 364/suivi eleve refacto sub topic

README.md
description readme pour la transition
https://github.com/OPEN-ENT-NG/competences/issues/101
=> docs(README): add extra description transition

.github/workflows/dev-check-repository.yml, docker-compose.yml
=> chore(node): upgrade node version docker

src/main/java/fr/openent/competences/bean/NoteDevoir.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/BilanPeriodiqueController.java, src/main/java/fr/openent/competences/controllers/LSUController.java, src/main/java/fr/openent/competences/model/Group.java, src/main/java/fr/openent/competences/model/Matiere.java, src/main/java/fr/openent/competences/model/Model.java, src/main/java/fr/openent/competences/model/Service.java, src/main/java/fr/openent/competences/model/Structure.java, src/main/java/fr/openent/competences/model/SubTopic.java, src/main/java/fr/openent/competences/model/Teacher.java, src/main/java/fr/openent/competences/service/BilanPeriodiqueService.java, src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/SubTopicService.java, src/main/java/fr/openent/competences/service/UtilsService.java, src/main/java/fr/openent/competences/service/impl/DefaultBilanPerioqueService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultSubTopicService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
Bulletins are now calculating their averages with subtopics coefficients (this is the second part of the subtopic evolution)
Compétences -> Générer les bulletins -> print a bulletin and check if the averages of student/class are the right ones depending on the subtopics set up in viescolaire module -> Compétences -> Modalités des services -> Click on a service.
[EVAL-332](https://jira.support-ent.fr/browse/EVAL-332)
=> feat: eval-332 bulletins are now calculating their averages with subtopics coefficients

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/DevoirController.java, src/main/java/fr/openent/competences/controllers/UtilsController.java, src/main/java/fr/openent/competences/security/AccessConseilDeClasse.java, src/main/java/fr/openent/competences/security/utils/WorkflowActions.java
Adding authentication security on apis.
EVAL-376 : https://jira.support-ent.fr/browse/EVAL-376
=> fix(SQLSecurity): #EVAL-376 adding missing authentication on api

src/main/java/fr/openent/competences/bean/StatClass.java, src/main/java/fr/openent/competences/bean/StatEleve.java, src/main/java/fr/openent/competences/bean/StatMat.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/NoteController.java, src/main/java/fr/openent/competences/service/ExportBulletinService.java, src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/UtilsService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/models/teacher/Eleve.ts
Releve Periodique averages are now being calculated by taking in account subtopics coefficients. 
Relevé périodique -> Chose a group+period+topic -> Check Moy Auto + Moy Finale. Can also check details by clicking on the 
pencil on the right of a line.
[EVAL-331](https://jira.support-ent.fr/browse/EVAL-331)
=> eval-331 : moyenne releve periodique

src/main/java/fr/openent/competences/service/impl/DefaultTransitionService.java
Ajout de la condition pour le calcul des compétences notes lors de la transition d'année
[EVAL-334](https://jira.support-ent.fr/browse/EVAL-334)
=> EVAL-334 apply option Skilll Average to year Transition

src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
Suivi Classe averages are now being calculated by taking in account subtopics coefficients.
Suivi Classe -> Chose a group+period -> Moyenne tab -> Check the frontpage + CSV + PDF.
[EVAL-365](https://jira.support-ent.fr/browse/EVAL-365)
=> eval-365 : moyenne suivi classe

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/service/impl/DefaultExportService.java, src/main/resources/public/template/pdf/releve-eleve.pdf.xhtml, src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts, src/main/resources/public/ts/utils/functions/average.ts
Suivi Eleve averages are now being calculated by taking in account subtopics coefficients.
Suivi Classe -> Chose a group+period+student -> Suivi des notes tab -> Check the frontpage + PDF.
[EVAL-364](https://jira.support-ent.fr/browse/EVAL-364)
=> eval-364 : moyenne suivi eleve

src/main/resources/public/sass/global/sniplets/_services.scss, src/main/resources/public/template/behaviours/sniplet-paramServices.html
Alignement des icônes
/!\ Il faudra à termes mettre tout le tableau en flex (revoir css du composant)
Vérifier que l'icône des sous matières soit bien alignés avec les autres icônes 
https://entsupport.gdapublic.fr/browse/EVAL-359
=> fix(service): #EVAL-359 fix display icon

src/main/resources/sql/036-match_class_id_transition.sql
https://github.com/OPEN-ENT-NG/competences/issues/106
=> fix(Transition):EVAL-373 alter table for SAAS

src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts
Si une competence est présente sur plusieurs domaines elle ne compte que pour 1
https://jira.support-ent.fr/browse/EVAL-342
=> fix(SuiviEleve):EVAL-342 competences with 2 domains still count for 1

src/main/java/fr/openent/competences/bean/StatMat.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/ExportPDFController.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/resources/public/template/pdf/releve-classe.pdf.xhtml, src/main/resources/public/template/pdf/releve-eleve.pdf.xhtml, src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/utils/functions/average.ts
Fixes to diverse things, such as Appreciation Professeurs screen not being calculated, front average not being correctly calculated, some rebase problems, ...
At this point, all the screens will be tested alltogether to ensure everything is functionnal.
=> eval-139 : final fixes

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/NoteController.java, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
Fixed averages being put to NN on Releve Periodique while modifying a mark.
Releve Periodique -> Try to change a mark and check if the new average is the correct one.
[EVAL-385](https://jira.support-ent.fr/browse/EVAL-385)
=> fix(sous-matiere) : eval-385 subtopics fix on releve periodique

src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
Fix assignment creation with ce account. When a subject is selected, no longer take older sub suject on it when they're unselected.
Log in with a CE account on "Compétences", then go to "Creér une évaluation". Find a class that has a subject containing a sub-subject, select it and then submit a single subject. Create the assessment and see if the correct subject with no subs is in the assessment.
[EVAL-382](https://jira.support-ent.fr/browse/EVAL-382)
=> fix(createDevoir): #EVAL-382 fix bug on creation when sub subject was selected

src/main/java/fr/openent/competences/service/impl/DefaultDevoirService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
Fixed an mobile API which didn't yet take in account subtopics coefficients.
[EVAL-381](https://jira.support-ent.fr/browse/EVAL-381)
=> fix(AppliMobile) : Eval-381 Take coeff of subtopic

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/EventBusController.java, src/main/java/fr/openent/competences/service/SubTopicService.java, src/main/java/fr/openent/competences/service/impl/DefaultSubTopicService.java
Subtopics are now deleted when deleting associated service.
Vie Scolaire -> Competences -> Modalité des services -> Delete a service and check in the DB if the subtopics linked to this service are not there.
[EVAL-139](https://jira.support-ent.fr/browse/EVAL-139)
[MVS-75](https://jira.support-ent.fr/browse/MVS-75)
=> feat(subtopics) : EVAL-139 Subtopics are now deleted when deleting associated service.

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/NoteController.java, src/main/java/fr/openent/competences/helpers/FutureHelper.java, src/main/java/fr/openent/competences/importservice/ExercizerImportNote.java, src/main/java/fr/openent/competences/importservice/Import.java, src/main/java/fr/openent/competences/importservice/ImportFile.java, src/main/java/fr/openent/competences/model/importservice/ExercizerStudent.java, src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/UtilsService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
Added the possibility to insert or update notes depending while importing an Exercizer-type CSV.
API testing /notes/:id/:typeImportService/csv/:classId/:devoirId, else wait for the front ticket.
[EVAL-398](https://jira.support-ent.fr/browse/EVAL-398)
=> feat(exercizer) : EVAL-398 Now insert or update notes depending on an Exercizer-type CSV.

src/main/resources/public/template/enseignants/bilan_periodique/display_suivi_acquis.html
Reduce space between subjects et sub-subjects to avoid more space for appreciation.
EVAL-247 : https://jira.support-ent.fr/browse/EVAL-247
=> fix(appreciation): EVAL-247 enlargement of the appreciation field

src/main/resources/public/ts/behaviours.ts
Deletes an outdated right.
Check the access of Viescolaire -> onglet Competences -> Modalités des services 
[EVAL-419](https://jira.support-ent.fr/browse/EVAL-419)
[MVS-88](https://jira.support-ent.fr/browse/MVS-88)
=> feat(droits) : #EVAL-419 Deletes an outdated right.

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/NoteController.java, src/main/java/fr/openent/competences/importservice/ExercizerImportNote.java, src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/UtilsService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java, src/main/resources/i18n/fr.json, src/main/resources/public/import/skeletonExercizer.csv, src/main/resources/public/template/enseignants/liste_notes_devoir/display_notes_devoir.html, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/directives/import-note/import-note.directive.ts, src/main/resources/public/ts/directives/import-note/import-note.html, src/main/resources/public/ts/models/teacher/Devoir.ts, src/main/resources/public/ts/services/note.service.ts
Fixed some inconsistencies between front and back, such as the URL used and some variables.
https://confluence.support-ent.fr/display/MN/%5BNotes%5D+Import+Exercizer
[EVAL-45](https://jira.support-ent.fr/browse/EVAL-45)
=> feat(exercizer) : #EVAL-45 Fix some inconsistencies between front and back.

src/main/resources/public/sass/global/specifics/_competences.scss, src/main/resources/public/template/enseignants/bulletin/lightbox-select-report-model.html
Improvement of fronts
https://jira.support-ent.fr/browse/EVAL-174
=> fix(BulletinModel) #EVAL-174: fix front returns

src/main/java/fr/openent/competences/constants/Field.java
Add magic string key to Field.java. We can now edit string and older magic string with new keys.
[EVAL-344](https://jira.support-ent.fr/browse/EVAL-344)
=> fix(magicString): #EVAL-344 implement Field.java with magicString key

src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
Fixes desync occuring because of old futures code, so changes that to a promise.
Generate a bulletin, if it exports it works.
[EVAL-426](https://jira.support-ent.fr/browse/EVAL-426)
=> fix(Bulletin) : #EVAL-426 Fixes desync occuring because of old futures code.

src/main/java/fr/openent/competences/controllers/UtilsController.java, src/main/java/fr/openent/competences/security/AccessIfMyStructure.java, src/main/java/fr/openent/competences/service/UtilsService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
add RessourceFilter on API user/list
toute l'application en tant que ce, professeurs, personnel, élèves et parents
[EVAL-431](https://jira.support-ent.fr/browse/EVAL-431)
- [ X] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X ] I have performed a self-review of my code
=> fix(security): EVAL-431 get Teachers

src/main/java/fr/openent/competences/Utils.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/BilanPeriodiqueController.java, src/main/java/fr/openent/competences/utils/MultiTeachersUtils.java
Filter subtitute by periode
https://jira.support-ent.fr/browse/EVAL-430
=> fix(BilanPeriodique)#Eval-430: subtitute teachers filter

src/main/java/fr/openent/competences/controllers/BilanPeriodiqueController.java, src/main/java/fr/openent/competences/controllers/ExportPDFController.java, src/main/java/fr/openent/competences/controllers/LSUController.java, src/main/java/fr/openent/competences/controllers/NoteController.java, src/main/java/fr/openent/competences/controllers/SubTopicController.java, src/main/java/fr/openent/competences/helpers/FutureHelper.java, src/main/java/fr/openent/competences/service/SubTopicService.java, src/main/java/fr/openent/competences/service/UtilsService.java, src/main/java/fr/openent/competences/service/impl/DefaultDevoirService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultSubTopicService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
Fixes some subjects not taking in account subtopic coeffs PDF export when the marks were on a multi-class group.
Suivi Classe -> Moyennes tab -> Check if the pdf has the same averages as in Releve Periodique
[EVAL-436](https://jira.support-ent.fr/browse/EVAL-436)
=> fix(ExportPDF) : #EVAL-436 Fixes some subjects not taking in account subtopic coeffs PDF export when the marks were on a multi-class group.

src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
ne pas modifier owner du devoir lors de l'update si on est un professeur
lorsqu'un remplaçant modifie un ou des devoirs du service le titulaire a toujours accès à son ou ses devoirs
[EVAL-433](https://jira.support-ent.fr/browse/EVAL-433)
=> fix(updateDevoir) : #EVAL-433 if teacher do not update owner

src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
Fixes some subjects not taking in account subtopic coeffs on front and CSV when the marks were on a multi-class group
Suivi Classe -> Moyennes tab -> Check if the front and the CSV has the same subjects and averages as the PDF
[https://jira.support-ent.fr/browse/EVAL-437](https://jira.support-ent.fr/browse/EVAL-437)
=> fix(SuiviClasse) : #EVAL-437 Fixes some subjects not taking in account subtopic coeffs on front and CSV when the marks were on a multi-class group

src/main/java/fr/openent/competences/controllers/UtilsController.java, src/main/java/fr/openent/competences/security/AccessIfMyStructure.java, src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts, src/main/resources/public/ts/services/classes.service.ts
Fixes multiclasses group not taking in account their subtopics coefficients on front + CSV of Suivi Eleve
Check Suivi Eleve -> Moyennes, with marks put on multiclasses group and with a coefficiented subtopic.
[EVAL-452](https://jira.support-ent.fr/browse/EVAL-452)
=> fix(SuiviEleve) : EVAL-452 Fixes multiclasses group not taking in account their subtopics coefficients on front + CSV of Suivi Eleve

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/service/impl/DefaultExportService.java, src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts
Fixes multiclasses group not taking in account their subtopics coefficients on PDF of Suivi Eleve.
Suivi Eleve-> Suivi des Notes tab -> Check if the PDF has the right subjects and averages.
[EVAL-454](https://jira.support-ent.fr/browse/EVAL-454)
=> fix(ReleveNote) : EVAL-454 Fixes multiclasses group not taking in account their subtopics coefficients on PDF of Suivi Eleve.

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/ExportPDFController.java, src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts
Fixes averages PDF of Suivi Classe encountering an error if a group tried to do the export.
Suivi Classe -> Try to export a PDF in the "Moyennes" tab with a class and then with a group.
[EVAL-453](https://jira.support-ent.fr/browse/EVAL-453)
=> fix(SuiviClasse) : EVAL-453 Fixes averages PDF of Suivi Classe encountering an error if a group tried to do the export.

build.gradle, src/main/java/fr/openent/competences/controllers/ExportPDFController.java, src/main/java/fr/openent/competences/security/AccessSuiviClasse.java, src/main/java/fr/openent/competences/security/utils/WorkflowActionUtils.java, src/main/java/fr/openent/competences/security/utils/WorkflowActions.java, src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts, src/test/java/fr/openent/competences/security/AccessEvaluationFilterTest.java, src/test/java/fr/openent/competences/security/AccessSuiviClasseTest.java
Security checks for ExportPDFController's routes.
Unit tests and Postman
[#EVAL-456](https://jira.support-ent.fr/browse/EVAL-456)
=> fix(security): #EVAL-456 security on ExportPDFController

src/main/java/fr/openent/competences/controllers/MatiereController.java, src/main/java/fr/openent/competences/security/AccessIfMyStructure.java, src/main/java/fr/openent/competences/security/AdministratorRight.java, src/main/java/fr/openent/competences/security/modelbulletinrights/AccessExportModelBulletin.java, src/main/java/fr/openent/competences/security/modelbulletinrights/AccessExportModelBulletinStructureId.java, src/main/java/fr/openent/competences/security/modelbulletinrights/GetModelExportBulletin.java, src/main/java/fr/openent/competences/security/modelbulletinrights/PostModelExportBulletin.java, src/main/java/fr/openent/competences/security/modelbulletinrights/UserIdModelExportBulletin.java, src/main/java/fr/openent/competences/security/utils/WorkflowActionUtils.java, src/main/java/fr/openent/competences/security/utils/WorkflowActions.java, src/main/resources/public/ts/sniplets/orderShowSubject.ts, src/main/resources/public/ts/sniplets/renameSubject.ts, src/test/java/fr/openent/competences/security/AccessIfMyStructureTest.java, src/test/java/fr/openent/competences/security/AccessSuiviClasseTest.java, src/test/java/fr/openent/competences/security/AdministratorRightTest.java
Security checks for MatiereController's routes
[#EVAL-457](https://jira.support-ent.fr/browse/EVAL-457)
=> fix(security): #EVAL-457 security on MatiereController

src/main/java/fr/openent/competences/controllers/NiveauDeMaitriseController.java, src/main/resources/public/ts/models/eval_niveau_comp.ts
Handle route's security on NiveauDeMaitriseController
[#EVAL-458](https://jira.support-ent.fr/browse/EVAL-458)
=> fix(security): #EVAL-458 security on NiveauDeMaitriseController

src/main/java/fr/openent/competences/controllers/ArchiveBFCController.java, src/main/java/fr/openent/competences/controllers/ArchiveBulletinController.java, src/main/java/fr/openent/competences/security/HasExportLSURight.java
Handling routes's security with ResourceFilter on  ArchiveBFCController and ArchiveBulletinController
[#EVAL-459](https://jira.support-ent.fr/browse/EVAL-459)
=> fix(security): #EVAL-459 security on ArchiveBFCController and ArchiveBulletinController

src/main/java/fr/openent/competences/controllers/BFCController.java, src/main/java/fr/openent/competences/security/AccessIfMyStructure.java, src/main/java/fr/openent/competences/security/CanUpdateNiveauEnsCpl.java, src/main/java/fr/openent/competences/security/utils/WorkflowActions.java, src/main/resources/public/ts/models/eval_ens_complement_mdl.ts, src/main/resources/public/ts/models/eval_langue_culture_regionale_mdl.ts
Changing resourceFilter on some routes.
Testing routes ad variables with breakpoints in browser, 
[#EVAL-460](https://jira.support-ent.fr/browse/EVAL-460)
=> fix(security): #EVAL-460 security on BFCController

src/main/java/fr/openent/competences/security/AccessSuiviClasse.java, src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts, src/main/resources/public/ts/models/teacher/Utils.ts, src/test/java/fr/openent/competences/security/AccessEvaluationFilterTest.java
Adding structure Id on in front api
[#EVAL-456](https://jira.support-ent.fr/browse/EVAL-456)
=> fix(security): #EVAL-456 add structure id in query params

src/main/java/fr/openent/competences/helpers/FutureHelper.java, src/main/java/fr/openent/competences/service/AppreciationService.java, src/main/java/fr/openent/competences/service/CompetenceNoteService.java, src/main/java/fr/openent/competences/service/ElementProgramme.java, src/main/java/fr/openent/competences/service/MatiereService.java, src/main/java/fr/openent/competences/service/UtilsService.java, src/main/java/fr/openent/competences/service/impl/DefaultAppreciationService.java, src/main/java/fr/openent/competences/service/impl/DefaultCompetenceNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultElementProgramme.java, src/main/java/fr/openent/competences/service/impl/DefaultMatiereService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
refacto code : methods use Promises and return Future 
vue du relevé périodique et export pdf et csv de ce relevé, pour toutes les périodes
[EVAL-462](https://jira.support-ent.fr/browse/EVAL-462)
=> refactor() : EVAL-462 use Promise and Future

src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
En lien avec la PR https://github.com/OPEN-ENT-NG/vie-scolaire/pull/83
Ce commit permet de rectifier pour l'API POST `/export/bulletins`
Elle corrige l'exception : 
```
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at io.vertx.core.json.JsonArray.getJsonObject(JsonArray.java:208)
at fr.openent.competences.service.impl.DefaultExportBulletinService$20.handle(DefaultExportBulletinService.java:2760)
fr.openent.competences.service.impl.DefaultExportBulletinService$20.handle(DefaultExportBulletinService.java:2756)
at fr.openent.competences.Utils.lambda$getGroupesClasse$1(Utils.java:121)
at fr.wseduc.webutils.Utils.lambda$handlerToAsyncHandler$0(Utils.java:195)
```
Qui est appelé par la méthode …
=> fix(viesco): #MVS-100 fix eb reply potential exception IndexOutOfBounds

src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
refactor add Promise and Future
view "relevé périodique" and pdf csv export
[EVAL-463](https://jira.support-ent.fr/browse/EVAL-463) continuation [EVAL-462](https://jira.support-ent.fr/browse/EVAL-462)
=> Eval 463 part2

src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts, src/main/resources/public/ts/models/teacher/BilanPeriodique.ts
Fix from returns after testing dev-security.
Missing parameter in frontend for 2 API :
- @Get("/recapEval/print/:idClasse/export")
- @Post("/releve/exportTotale")
On test, be sure to not have an 401 (unauthorize) error on these route.
[EVAL-485](https://jira.support-ent.fr/browse/EVAL-485)
=> fix(security): #EVAL-485 fix returns dev-security

src/main/java/fr/openent/competences/Competences.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/security/utils/FilterAppreciationUtils.java, src/main/java/fr/openent/competences/security/utils/FilterCompetenceNoteUtils.java, src/main/java/fr/openent/competences/security/utils/FilterDevoirUtils.java, src/main/java/fr/openent/competences/security/utils/FilterNoteUtils.java, src/main/java/fr/openent/competences/service/impl/DefaultDevoirService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/utils/HomeworkUtils.java, src/main/resources/public/template/enseignants/releve_notes/display_releve.html, src/main/resources/public/ts/models/teacher/ReleveNote.ts
ajout des notes des élèves pour chaque devoir de la période et de la matière
refacto : magic string de la competence -> Field
export csv avec des devoirs sur la période, avec des notes ou des annotations
export csv sans devoir
[EVAL-464](https://jira.support-ent.fr/browse/EVAL-464) première partie du ticket [EVAL-294](https://jira.support-ent.fr/browse/EVAL-294)
=> feat() : #Eval 464  add notes in csv

src/main/java/fr/openent/competences/controllers/ExportPDFController.java
Added condition to avoid nullPointerException when matter is not matching.
Compétence -> Suivi classe -> Pick "Classe / Groupe" and "Période" and then click on tab "Appréciations Professeurs".
[EVAL-485](https://jira.support-ent.fr/browse/EVAL-485)
=> fix(security): #EVAL-485 return from dev-security tests

src/main/java/fr/openent/competences/controllers/NoteController.java
Modify API parameter spelling to match with resource filter [AccessEvaluationFilter](https://github.com/OPEN-ENT-NG/competences/blob/fcaa8e7ab5fdcae38ab17bf162c26ac718f31bcc/src/main/java/fr/openent/competences/security/AccessEvaluationFilter.java#L50).
Module "Compétences" --> select an eval --> click on "Importer un fichier csv" --> add a file --> validate it
[EVAL-487](https://jira.support-ent.fr/browse/EVAL-487)
=> fix(security): #EVAL-487 modify api parameter spelling

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/NoteController.java, src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultBilanPerioqueService.java, src/main/java/fr/openent/competences/service/impl/DefaultDevoirService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/resources/i18n/fr.json, src/main/resources/public/template/enseignants/releve_notes/display_releve.html, src/main/resources/public/ts/models/teacher/AppreciationMatiere.ts, src/main/resources/public/ts/models/teacher/ReleveNote.ts
- ajout des appréciations précédentes dans l'export csv du relevé périodique d'une classe ou groupe et d'une matière
relevé périodique : choisir une classe, une période et une matière -> export cocher ds la popup appréciation des périodes précédentes. Les appréciations , si elles sont existantes doivent être affichées dans le csv et à partir du trimestre 2 ou du semestre 2
[EVAL-466](https://jira.support-ent.fr/browse/EVAL-466) lié [EVAL-294](https://jira.support-ent.fr/browse/EVAL-294)
=> feat: #Eval 466 add previous appreciations in csv export

src/main/java/fr/openent/competences/controllers/AnnotationController.java
Add check of structure on AnnotationController for the route : @Get("/annotations")
[#EVAL-439](https://jira.support-ent.fr/browse/EVAL-439)
=> fix(security):  #EVAL-439 add api security on annotations route

src/main/resources/public/ts/models/common/MultiTeaching.ts
Added parameter in request to match with back end security added in [MVS-102](https://github.com/OPEN-ENT-NG/vie-scolaire/pull/85)
Detailled in this [PR](https://github.com/OPEN-ENT-NG/vie-scolaire/pull/85)
[EVAL-486](https://jira.support-ent.fr/browse/EVAL-486) related to [MVS-102](https://jira.support-ent.fr/browse/MVS-102)
=> fix(security): #EVAL-486 added parameter in request to match with #MVS-102 security

src/main/java/fr/openent/competences/controllers/DomaineController.java
Added resource filter AccessIfMyStructure on one API to secure it.
Unit tests already done.
Module Compétence -> "Créer une évaluation" -> onglet "Compétences" -> Déplier une compétence -> petit signe +
[EVAL-482](https://jira.support-ent.fr/browse/EVAL-482)
=> fix(security): #EVAL-482 add resource filter on API

src/main/java/fr/openent/competences/controllers/DigitalSkillsController.java, src/main/resources/public/ts/models/teacher/digital_skills/DigitalSkills.ts
Added parameter in front end to match with security added in back end on one route of this controller.
Security file in back end already exist and ressource filter is applied.
On tests, try out differents ways to test if the security work well and don't have unexpected "401 (unauthorize)" error.
[EVAL-481](https://jira.support-ent.fr/browse/EVAL-481)
=> fix(security): #EVAL-481 added right resource filter on api for security

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java, src/main/java/fr/openent/competences/security/AccessChildrenParentFilterEtablissementId.java, src/main/java/fr/openent/competences/security/AccessIfMyStructure.java, src/main/java/fr/openent/competences/security/utils/WorkflowActionUtils.java
Change securedAction Authenticated to resource filter on route @Get("/competence/notes/bilan/conversion").
This resource filter checks the structure.
- On competences' module, choose a student in "suivi eleve" menu and verify response 401 if not authorized.
[EVAL-479](https://jira.support-ent.fr/browse/EVAL-479)
=> fix(security): #EVAL-479 improve security on CompetenceNoteController

src/main/java/fr/openent/competences/controllers/CompetenceController.java
Add reource filter on @Get("/competences/last/devoir/") api to check whether user has the workflow right : "competences.create.evaluation"
[#EVAL-478](https://jira.support-ent.fr/browse/EVAL-478)
=> fix(security): #EVAL-478 improve security of competences' api for CompetenceController

src/main/java/fr/openent/competences/controllers/SubTopicController.java, src/main/java/fr/openent/competences/security/AccessIfMyStructure.java
On api @Get("/subtopics/services/:idStructure") :  Change Authenticated securedAction to resourceFilter which checks user's structure. This change prevents unauthorized people from accessing this route.
[#EVAL-446](https://jira.support-ent.fr/browse/EVAL-446)
=> fix(security): #EVAL-446 add resource filter on route get /subtopics/services/:idStructure in SubTopicController

src/main/java/fr/openent/competences/controllers/EnseignementController.java, src/main/resources/public/ts/models/common/DefaultEnseignement.ts, src/main/resources/public/ts/models/eval_parent_mdl.ts, src/main/resources/public/ts/models/teacher/SuiviCompetence.ts, src/main/resources/public/ts/models/teacher/SuiviCompetenceClasse.ts
Added resource filter on one route : 
- @Get("/enseignements")
Added parameter "idStructure" in front end controller.
Compétence -> Suivi Classe -> select "Classe / Groupe" -> select "Période" -> check "Vue par enseignements"
[EVAL-484](https://jira.support-ent.fr/browse/EVAL-484)
=> fix(security): #EVAL-484 added resource filter & parameter in EnseignementController

src/main/java/fr/openent/competences/controllers/ElementBilanPeriodiqueController.java, src/main/resources/public/ts/models/teacher/BilanPeriodique.ts
Added resource filter to ElementBilanPeriodiqueController on two routes :
- @Get("/elementsBilanPeriodique")
- @Get("/elementsBilanPeriodique/enseignants")
[EVAL-483](https://jira.support-ent.fr/browse/EVAL-483)
=> fix(security): #EVAL-483 add resource filter to ElementBilanPeriodiqueController

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/UtilsController.java, src/main/java/fr/openent/competences/security/AccessParamLinkGroupCycleStructure.java, src/main/java/fr/openent/competences/security/AccessStructureIsParent.java, src/main/resources/public/ts/models/eval_parent_mdl.ts, src/main/resources/public/ts/sniplets/linkGroupCycle.ts, src/test/java/fr/openent/competences/security/AccessIfMyStructureTest.java, src/test/java/fr/openent/competences/security/AccessParamLinkGroupCycleStructureTest.java, src/test/java/fr/openent/competences/security/AccessStructureIsParentTest.java
- On route @Get("/types") : add ResourceFilter to check the structure
- On route @Get("/mainteachers/:idStructure") : add ResourceFilter to check the structure
- On route @Get("/enfants") : add resource filter AccessStructureIsParent to verify the structure and the the type of user (must be "Relative")
- On route @Post("/link/check/data/classes") : add resource filter AccessParamLinkGroupCycleStructure to check structure and the user's right of type "competences.paramLinkGroupCycle". The front file linkGroupCycle.ts has been modified to pass structure id on query param.
- On route @Post("/eleve/evenements"): set workflow right "can_update_retards_and_absences"
- On route @Post("/graph/img"): set workflow right "can_access_export_bulletin"
Finally, i created unit tests for the …
=> fix(security): #EVAL-470 improve security on APIs of utilsController

src/main/resources/public/ts/directives/ProportionSuiviCompetence.ts
Fix color bars not displaying on student report.
Suivi Eleve -> Check if the color bars are there and with the right numbers/color.
[EVAL-461](https://jira.support-ent.fr/browse/EVAL-461)
=> fix(report-class) : #EVAL-461 Fix color bars not displaying on student report.

src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
export bulletin sur un élève où l'on a ajouté un parent
[EVAL-504](https://jira.support-ent.fr/browse/EVAL-504)
=> fix(ExportBulletin): EVAL-504

src/main/java/fr/openent/competences/controllers/DevoirController.java, src/main/java/fr/openent/competences/controllers/UtilsController.java, src/main/java/fr/openent/competences/service/UtilsService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
Delete unused API : @Get("/mainteachers/:idStructure")
Modify resource filter for @Get("/devoir/:idDevoir/moyenne")
@Get("/devoir/:idDevoir/moyenne") Module "Compétence" -> "Liste des évaluations" -> choose an assessment
[EVAL-506](https://jira.support-ent.fr/browse/EVAL-506)
=> fix(security): #EVAL-506 remove unused API and change resource filter

src/main/resources/public/template/enseignants/suivi_competences_classe/content_vue_suivi_classe.html, src/main/resources/public/template/enseignants/suivi_eleve/tabs_follow_eleve/follow_items/content_vue_suivi_eleve.html, src/main/resources/public/template/parent_enfant/bilan_competences/content_vue_bilan_eleve.html, src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts, src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts, src/main/resources/public/ts/directives/ProportionSuiviCompetence.ts, src/main/resources/public/ts/directives/teachingsSkills.ts, src/main/resources/public/ts/models/teacher/SuiviCompetenceClasse.ts, src/main/resources/public/ts/models/teacher/Utils.ts
ajout de booléen ou réctification des conditions et pour le suivi classe, séparation des calculs pour ce cas
voir le tickets si join
[EVAL-476](https://jira.support-ent.fr/browse/EVAL-476)
=> fix(suivi): EVAL-476 domaine and enseignement suivi classe et suivi eleve

src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/models/teacher/SuiviCompetence.ts, src/main/resources/public/ts/models/teacher/Utils.ts
ajout du type de rapport demandé : par défaut dans le suivi élève ce sera seulement les notes
suivi élève -> onglet suivi des notes ->  exporter le relevé de notes de la classe au format pdf
=> fix(exportReport): EVAL-512 add the type of report in the studient follow-up studient

src/main/resources/public/template/enseignants/bilan_periodique/left-side-bilanperiodique.html, src/main/resources/public/ts/controllers/eval_bilan_periodique_ctl.ts, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/models/teacher/Classe.ts, src/main/resources/public/ts/models/teacher/DevoirCollection.ts, src/main/resources/public/ts/models/teacher/Utils.ts
Lorsque utilisateur multi-établissement change d'établissement sur la vue du conseil de classe, réinitialise là vue avec les bons paramètres (sélection de classes de la structure, etc).
- Se connecter avec un utilisateur multi-établissement.
- Aller sur la vue du conseil de classe.
- Sélectionner une classe, un période puis un élève
- Changer d'établissement
- La vue est réinitialiser et les sélecteurs se sont adaptés à l'établissement en cour.
[Jira - EVAL-492](url)
=> fix(class-council) #EVAL-492 fix structure switch when current user is multi-structure

src/main/java/fr/openent/competences/bean/StatMat.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
ajout d'une condition sur le coefficient du devoir
avoir un devoir avec un coefficient zéro -> conseil de classe -> onglet Graph
[EVAL-502](https://jira.support-ent.fr/browse/EVAL-502)
=> fix(graphConseilDeClasse) : EVAL-502  filter evaluations with zero coefficient

src/main/java/fr/openent/competences/controllers/ExportBulletinController.java
ajout du bon droit de resource
menu Export -> sur la seconde partie, choisir bulletins et sélectionner une ou plusieurs périodes et cliquer sur générer l'archive.
[EVAL-517](https://jira.support-ent.fr/browse/EVAL-517)
=> fix(ExporsArchives) : EVAL-517 add the right resource filter

src/main/java/fr/openent/competences/Competences.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/BilanPeriodiqueController.java, src/main/java/fr/openent/competences/controllers/LSUController.java, src/main/java/fr/openent/competences/controllers/NoteController.java, src/main/java/fr/openent/competences/helpers/FutureHelper.java, src/main/java/fr/openent/competences/model/SkillModel.java, src/main/java/fr/openent/competences/model/achievements/AchievementsProgress.java, src/main/java/fr/openent/competences/model/achievements/AchievementsSubject.java, src/main/java/fr/openent/competences/service/BilanPeriodiqueService.java, src/main/java/fr/openent/competences/service/ServiceFactory.java, src/main/java/fr/openent/competences/service/impl/DefaultBilanPerioqueService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java, src/main/java/fr/openent/competences/service/impl/DefaultStructureOptions.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/enseignants/bilan_periodique/display_suivi_acquis.html, src/main/resources/public/ts/controllers/eval_bilan_periodique_ctl.ts, src/main/resources/public/ts/models/achievements.model.ts, src/main/resources/public/ts/models/model.ts, src/main/resources/public/ts/models/teacher/SuiviDesAcquis.ts, src/main/resources/public/ts/services/achievementsProgressService.ts, src/test/java/fr/openent/competences/service/impl/DefaultBilanPerioqueServiceTest.java
Sur la page du conseil de classe, affiche désormais le pourcentage de validation des compétences par enseignements.
- seules les compétences évalués comptes.
- les compétences validés: 3/4 ou 4/4.
- ne tiens pas compte de la surcharge d'un enseignement.
https://confluence.support-ent.fr/display/MN/%5BNote%5D+Bilan+Periodique
- Aller sur la page du conseil de classe.
- Si ce n'est pas déjà fait, checker l'option "Comp. validées (%)" des options du tableau (bouton  bleu avec flèche).
- Observer les différents pourcentages.
[Jira - EVAL-339](https://jira.support-ent.fr/browse/EVAL-339)
=> feat(): #EVAL-339 add skills validated percentage in class council

src/main/java/fr/openent/competences/Competences.java, src/main/java/fr/openent/competences/bean/StatMat.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
les notes des évaluations fomatives ne sont pas comptabilisées dans le calcul de la moyenne de l'élève et de la classe
voir le ticket ci-dessous
[EVAL-503](https://jira.support-ent.fr/browse/EVAL-503)
=> fix() : EVAL-503 do not count marks from formative assessments

src/main/resources/public/ts/models/teacher/Classe.ts, src/main/resources/public/ts/models/teacher/Eleve.ts
filtre des élèves supprimés dans un groupe
créer un évaluation sur un groupe, seuls les élèves supprimés dans la période doivent être présents
[EVAL-518](https://jira.support-ent.fr/browse/EVAL-518)
=> fix() : EVAL-518 fiter deleted students

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/DevoirController.java, src/main/java/fr/openent/competences/enums/Common.java, src/main/java/fr/openent/competences/service/impl/DefaultDevoirService.java, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/models/teacher/Devoir.ts
ajout de magic string 
ajout du champs formative dans les requêtes qui récupère les devoirs en fonction des profils
1. se connecter avec tous les utilisateurs
2. pour un ce ou un prof : relevé périodique, choisir une classe, période et matière où il y a une évaluation formative
[EVAL-528](https://jira.support-ent.fr/browse/EVAL-528)
=> fix(periodicStatement) #EVAL-528 not update the student's average when entering scores on a formative evaluation

src/main/java/fr/openent/competences/Competences.java, src/main/java/fr/openent/competences/Utils.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/ExportPDFController.java, src/main/java/fr/openent/competences/service/AverageService.java, src/main/java/fr/openent/competences/service/ServiceFactory.java, src/main/java/fr/openent/competences/service/SyntheseBilanPeriodiqueService.java, src/main/java/fr/openent/competences/service/impl/DefaultAverageService.java, src/main/java/fr/openent/competences/service/impl/DefaultSyntheseBilanPeriodiqueService.java, src/main/resources/i18n/fr.json, src/main/resources/public/template/enseignants/suivi_competences_classe/content.html, src/main/resources/public/template/pdf/recap_moys_eleves_par_matiere_classe.pdf.xhtml, src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts, src/test/java/fr/openent/competences/service/impl/DefaultAverageServiceTest.java
Ajout (optionnel) de la synthèse sur l'exporte pdf des moyennes des élèves d'une classe. 
- En tant que Ce, sur la page "Suivi Classe"
- Après sélection d'une classe et d'une période, cliquer sur l'icone de téléchargement
- (Au moins un élève de la classe doit avoir une synthèse remplie pour la période sélectionnée)
- Dans la rubrique "Exporter au format PDF", sélectionner "Tableau des moyennes des élèves de la classe"
- Cliquer sur exporter
- observer l'ajoute des synthèses de chaque élèves
[Jira - EVAL-227](https://jira.support-ent.fr/browse/EVAL-227)
=> feat(class-report): #EVAL-227 add summaries at students averages pdf export

src/main/resources/public/template/enseignants/bilan_periodique/left-side-bilanperiodique.html
ajout d'une vérification dans le HTML
conseil de classe -> choisir une classe de 6ème, une période et un élève -> onglet bfc -> l'encart pour évaluer les enseignements de compléments ne doit pas présent.
[EVAL-534](https://jira.support-ent.fr/browse/EVAL-534)
=> fix(conseilClass) #EVAL-534 show complementary teaching only for cycle 4 on the bfc tab

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
le nombre de notes de compétences obtenu pour un niveau est comptabilisé en fonction du type d'évaluation (formative F) note 
suivi classe -> choisir une classe et une période -> choisir d'exporter -> choisir Le relevé de notes des élèves de la classe : compétences ou Notes et compétences.
Vérifier aussi les exports pdf : 
- Tableau récapitulatif des niveaux acquis par domaine des élèves
- Listes récapitulatives des compétences évaluées par domaine ou enseignement des élèves
[EVAL-529](https://jira.support-ent.fr/browse/EVAL-529)
=> fix(followupClass) #EVAL-529 add the letter F for skill score from formative assessment

src/main/resources/public/ts/controllers/eval_parent_releve_ctrl.ts
ajout du calcul avec les sous matières comme pour les professeurs et les CE
Avoir des devoirs sur des sous matières. Se connecter en tant que parent ou élève. Choisir le bilan périodique dans le menu.
[EVAL-533](https://jira.support-ent.fr/browse/EVAL-533)
=> fix(periodeStatement) #EVAL-533 calculate the average with subtopics for relatives and students

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/service/impl/DefaultTransitionService.java
Ajout de la suppression de la table services_subtopic lors du workflow after transition.
- Avant transition, vérifier qu'il existe des données dans services_subtopic.
- Une fois la transition faite, vérifier que cette table est vidée. (jusqu'à /competences/transition/after)
[Jira - EVAL-527](https://jira.support-ent.fr/browse/EVAL-527)
=> feat(transition): #EVAL-527 add truncate services_subtopic at after transition

src/main/java/fr/openent/competences/service/impl/DefaultTransitionService.java
Lorsque la relation competences_devoirs est créer pour des données de transition, filter sur les identifiant des devoirs récement créés, afin de ne pas dupliquer les relations des transitions antérieurs.
Réaliser la transition sur des données de 2 années différentes.
```sql
SELECT NOT EXISTS(
SELECT id_devoir, id_competence, count(index)
FROM notes.competences_devoirs
GROUP BY id_devoir, id_competence
HAVING COUNT(index) > 1
)
```
la requête ci-dessus doit répondre true. Elle compte le nombre de doublons (il ne doit pas y en avoir).
[Jira - EVAL-392](https://jira.support-ent.fr/browse/EVAL-392)
=> fix(transition): #EVAL-392 duplicate "competences_devoirs" is no more possible after multiple transitions

src/main/java/fr/openent/competences/controllers/ExportPDFController.java, src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
nouvelle requête pour récupérer que les notes des devoirs de type évaluation
suivi classe -> onglet appréciation (front) ,export pdf et export csv
[EVAL-522](https://jira.support-ent.fr/browse/EVAL-522)
=> fix(follow-upStudent) EVAL-522 filter formative evaluation average tab

src/test/java/fr/openent/competences/service/impl/DefaultNoteServiceTest.java
ajout des tests unitaires de la requête ajoutée dans le ticket ci-dessous
suivi classe -> onglet appréciations
[EVAL-543](https://jira.support-ent.fr/browse/EVAL-543)
=> fix(): #EVAL-543 add tests

src/main/resources/public/sass/global/components/_competences.scss, src/main/resources/public/template/enseignants/bilan_periodique/display_bilan_periodique.html, src/main/resources/public/template/enseignants/bilan_periodique/left-side-bilanperiodique.html, src/main/resources/public/template/enseignants/suivi_eleve/left_side.html, src/main/resources/public/ts/controllers/eval_bilan_periodique_ctl.ts, src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/models/teacher/Classe.ts, src/main/resources/view-src/admin-parameter.html, src/main/resources/view-src/competences.html, src/main/resources/view-src/eval_parents.html, src/main/resources/view-src/eval_teacher.html
Prise en compte des élèves supprimés sur le suivi élève et conseil de classe
Vérifier la présence des élèves supprimés dans les select des pages suivi éléve (élève en rouge) et conseil de classe.
Vérifier le passage de suivi classe au suivi élève : l'élève est bien selectionné
Vérifier que les élèves supprimés soient toujours en rouge dans le bilan périodique et la saisie des notes
=> fix(deletedStudent) : #Eval 537 no students deleted in the select tags for student following and the class council

src/main/java/fr/openent/competences/model/ParamsBulletins.java
retrieve the skill level parameters from the correct object
testexport bulletin avec le positionnement
[https://jira.support-ent.fr/browse/EVAL-422](EVAL-422)
=> fix(bulletin): #EVAL-422 add a legend for skill levels on the student's report

src/main/java/fr/openent/competences/enums/Common.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
add formative grades or grades with a coefficient of 0 to the list of homework grades for calculating statistics for each homework assignment
periodic statement : homework statistics must appear at the bottom of the table
[EVAL-532](https://jira.support-ent.fr/browse/EVAL-532)
=> fix(periodic statement) : #EVAL-532 keep formative scores or scores with a coefficient of 0 for calculing statistics for each assignment

build.sh, docker-compose.yml
https://jira.support-ent.fr/browse/EVAL-554
=> chore: fix yarn env build time #EVAL-554

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
Dans l'export PDF, on tiens désormais compte des moyennes finales "non notés".
- sur un trimestre, surcharger la moyenne final d'une matière à "NN"
- sur ce même trimestre, sur une autre matière, surcharger une matière avec une autre note (afin de tester la moyenne final)
- Dans Suivi Classe (sélectionner le groupe et le trimestre souhaité) -> Moyenne -> Bouton d'export -> exporter au format PDF
- Vérifier qu'on a bien que la surcharge de la moyenne avec une note, et que la matière ayant une moyenne finale à "NN" est bien présent.
[Jira - EVAL-395](https://jira.support-ent.fr/browse/EVAL-395)
=> fix(class-tracking) #EVAL-395: show subject final averages when they are "NN" in PDF

src/main/java/fr/openent/competences/Utils.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/DevoirController.java, src/main/java/fr/openent/competences/helpers/FutureHelper.java, src/main/java/fr/openent/competences/security/AccessChildrenParentFilter.java, src/main/java/fr/openent/competences/security/AccessChildrenParentFilterEtablissementId.java, src/main/java/fr/openent/competences/security/AccessCompetencesAdminTeacherPersonnel.java, src/main/java/fr/openent/competences/security/AccessStructureAdminTeacherFilter.java, src/main/java/fr/openent/competences/security/AccessStudentParentTeacherPersonnelFilter.java, src/main/java/fr/openent/competences/service/DevoirService.java, src/main/java/fr/openent/competences/service/MatiereService.java, src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/UtilsService.java, src/main/java/fr/openent/competences/service/impl/DefaultDevoirService.java, src/main/java/fr/openent/competences/service/impl/DefaultMatiereService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java, src/test/java/fr/openent/competences/security/AccessStructureAdminTeacherFilterTest.java, src/test/java/fr/openent/competences/service/impl/DefaultDevoirServiceTest.java
add Promise,Future, TU and filter formative assessments
liste des notes d'un élève pour une période
[EVAL-548](https://jira.support-ent.fr/browse/EVAL-548)
=> fix(AppliMobile) : #EVAL-548 omit formative assessments from the calculation of the average

src/test/java/fr/openent/competences/security/AccessCompetencesAdminTeacherPersonnelTest.java, src/test/java/fr/openent/competences/security/AccessConseilDeClasseStructureIdTest.java, src/test/java/fr/openent/competences/security/AccessConseilDeClasseTest.java, src/test/java/fr/openent/competences/security/AccessIfMyStructureTest.java, src/test/java/fr/openent/competences/security/AccessParamLinkGroupCycleStructureTest.java, src/test/java/fr/openent/competences/security/AccessStructureAdminTeacherFilterTest.java, src/test/java/fr/openent/competences/security/AccessSuiviClasseTest.java, src/test/java/fr/openent/competences/security/AdministratorRightTest.java, src/test/java/fr/openent/competences/security/IsRelativeTest.java, src/test/java/fr/openent/competences/service/BFCServiceTest.java, src/test/java/fr/openent/competences/service/impl/DefaultCompetenceNoteServiceTest.java
[EVAL-568](https://jira.support-ent.fr/browse/EVAL-568)
=> fix(TU) : #EVAL-568

src/main/java/fr/openent/competences/service/impl/DefaultDevoirService.java
Le problème initialement observé était une moyenne d'un élève noté NN sur l'endpoint mobile, alors qu'il avait 2 devoirs sur les sous-matières correspondantes:
- une à 12
- l'autre à NN
(on s'attend à une moyenne de 12, comme en front).
Après analyse, le service (professeur) auquel était associé le devoir noté à 12 n'existe plus (ou pas). Et la manière dont à été fait le script en back ne prend pas en compte les notes sans service. On se retrouve donc bien avec une moyenne NN.
Correction de ce cas afin que la note soit pris en compte (comme en front).
- Créer un service A sur une matière B ayant des sous matière sur un groupe C
- Créer un devoir lié à ce service
- Noter plusieurs élèves
- Créer un devoir sur la même matière B, groupe C mais sur un autre service D
- Noter les élèves, …
=> fix(mobile-average) #EVAL-576: calculate average including ratings with no more "service" as in front

src/main/resources/public/sass/global/components/_competences.scss, src/main/resources/public/sass/global/components/_mixins.scss, src/main/resources/public/sass/global/sniplets/_services.scss, src/main/resources/public/sass/index.scss, src/main/resources/public/template/behaviours/sniplet-paramServices.html, src/main/resources/public/ts/sniplets/paramServices.ts
Dans viescolaire, Sur la page competences, onglet Modalités des services, faire en sorte que l'engrenage de la partie "Evaluable" soit systématiquement cliquable, peut importe la taille de l'écran.
Voir la description.
[Jira - EVAL-582](https://jira.support-ent.fr/browse/EVAL-582)
=> fix(student-tracking) #EVAL-582: adapt sniplet service list style to make small screen accessible

src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
add idsGroupes on request to get final averages
moyenne final sur un élève d'un groupe sur une période-> suivi classe -> onglet moyenne, cette moyenne doit être présente
=> fix(SuiviClass_average) : no final avearges on a group

src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
if annual period average variable is always zero.
suivi-classe -> onglet moyenne -> période annuelle
retour du ticket [EVAL-545](https://jira.support-ent.fr/browse/EVAL-545) mais en réalité lié au dev du ticket [EVAL-542](https://jira.support-ent.fr/browse/EVAL-542)
=> fix(class-tracking) : #EVAL-542 annual period : no average on average tab

src/main/java/fr/openent/competences/service/impl/DefaultDevoirService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
add idPeriode
[EVAL-589](https://jira.support-ent.fr/browse/EVAL-589)
[EVAL-589](https://jira.support-ent.fr/browse/EVAL-589)
=> fix(class-tracking) : #EVAL-589 export pdf

src/main/resources/i18n/fr.json, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/models/teacher/Structure.ts
resolve student promise 
[EVAL-585](https://jira.support-ent.fr/browse/EVAL-585)
=> fix(access competence): #EVAL-585 consultation alone impossible

src/main/resources/public/ts/models/teacher/ReleveNote.ts
add name of homework on evaluation object
[EVAL-592](https://jira.support-ent.fr/browse/EVAL-592)
[EVAL-592](https://jira.support-ent.fr/browse/EVAL-592)
=> fix(transcript of records): #EVAL-592 display name of homework

src/main/resources/public/template/export/exports.html, src/main/resources/public/ts/controllers/eval_export_controller.ts
add reset to structure change
[EVAL-591](https://jira.support-ent.fr/browse/EVAL-591)
[EVAL-591](https://jira.support-ent.fr/browse/EVAL-591)
=> fix(BFC-BP LSU): #EVAL-591 multi structures

src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
[EVAL-598](https://jira.support-ent.fr/browse/EVAL-598)
[EVAL-598](https://jira.support-ent.fr/browse/EVAL-598)
=> fix(export of skills ): #EVAL-598 fix width calculation

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
This pull request introduces logic to handle special cases for student averages (`moyenne`) and final averages (`moyenneFinale`) when a student is in the third class level, along with a new constant for this special value. The main changes focus on ensuring that students in the third class level without an average are assigned a default value, and that final averages fall back to this value when not present.
**Student average handling:**
* In `DefaultNoteService.java`, when adding the third class level field for each student, if the student's average (`Field.MOYENNE`) is missing or set to `Field.NN`, it is set to `EA` if the student is in the third class level, otherwise it remains `NN`. (`[src/main/java/fr/openent/competences/service/impl/DefaultNoteService.javaL2894-R2904](diffhunk://#di …
=> feat(export): #EVAL-660 #EVAL-661 fix export average render
