OPEN-ENT-NG/competences

src/main/java/fr/openent/competences/service/ExportService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportService.java, src/main/resources/public/template/pdf/bulletin.pdf.xhtml, src/main/resources/public/template/pdf/bulletin_lycee.pdf.xhtml
https://entsupport.gdapublic.fr/browse/EVAL-191
Avant on faisait un `processTemplate` pour tous les élèves  et on faisait une génération PDF globale
Le problème étant que la pagination était accumulée pour tous les élèves
On fait un traitement pour faire le `processTemplate` et la génération PDF pour chaque élève.
A la fin de tout ce traitement, on merge tous les PDFs en un.
Résultat :
=> [SUITE EVAL-85]: feat(pdf): #EVAL-191 add generation pdf including pagination

.github/pull_request_template.md, deployment/competences/conf.json.template, gradle.properties, src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java, src/main/java/fr/openent/competences/service/impl/DefaultMongoExportService.java
Fix :
-  Bug lors de l'export Bulletin : "id_groupes" était parfois un string au lieu d un JsonArray
- Bug lors de l'export Bulletin : Présence d'un "$" au début d une clé JsonObject au moment de l insertion en mongo
https://entsupport.gdapublic.fr/browse/EVAL-325
=> fix:(Bulletins) : Eval 325/eleve suppr

src/main/java/fr/openent/competences/controllers/ExportPDFController.java, src/main/java/fr/openent/competences/controllers/NoteController.java, src/main/java/fr/openent/competences/service/impl/DefaultDevoirService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java, src/main/resources/public/template/enseignants/liste_notes_devoir/display_notes_devoir.html, src/main/resources/public/template/enseignants/suivi_eleve/tabs_follow_eleve/follow_items/content_vue_bilan_fin_cycle.html, src/main/resources/public/ts/controllers/eval_parent_ctl.ts, src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/models/common/Graph.ts, src/main/resources/public/ts/utils/functions/average.ts
Some averages were kept at a 0.xx value when we needed to have everything at a 0.x value, so the code (both front and back) where changed to respect everywhere the new format needed.
See the ticket comments for a list of concerned screens and exports to check.
https://entsupport.gdapublic.fr/browse/EVAL-192
=> feat(Moyenne): EVAL-192 Changing every averages to 0.x format instead of 0.xx.

src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts, src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts, src/main/resources/public/ts/models/teacher/Structure.ts, src/main/resources/public/ts/models/teacher/Utils.ts, src/main/resources/public/ts/utils/functions/average.ts
appliquer la moyenne des items de compétences dans le suivi élève dans les méthodes getMaxEvaluations dans eval_suivi_competences_classe_ctl.ts et setMaxCompetenceShow  dans Utils et eval_suivi_eleve_ctl.ts
[page confluence de l'analyse](https://confluence.support-ent.fr/pages/resumedraft.action?draftId=121700473&draftShareId=46e592c9-f90d-4c19-9604-d3bafbda2358&)
suivi élève onglet suivi des items et icône BFC pour toutes les périodes, pour un multi établissement
[EVAL-334](https://jira.support-ent.fr/browse/EVAL-334)
=> feat: Eval 334 apply option Skill Average to student follow-up 

src/main/resources/public/ts/models/sniplets/subtopicservice.service.ts
Fixed services params displaying a 1 when the coefficient is of 0.
VieScolaire -> Compétences -> Modalités des services -> Put a service subtopic coeff to 0, reload the page and check if it's still at 0.
[EVAL-384](https://jira.support-ent.fr/browse/EVAL-384)
=> fix(sous-matiere) : eval-384 fixed services params displaying a 1 when the coefficient is of 0

src/main/java/fr/openent/competences/Competences.java, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java, src/main/java/fr/openent/competences/controllers/StructureOptionsController.java, src/main/java/fr/openent/competences/service/CompetenceNoteService.java, src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/StructureOptionsService.java, src/main/java/fr/openent/competences/service/impl/DefaultBFCService.java, src/main/java/fr/openent/competences/service/impl/DefaultBilanPerioqueService.java, src/main/java/fr/openent/competences/service/impl/DefaultCompetenceNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultStructureOptions.java, src/main/java/fr/openent/competences/service/impl/DefaultTransitionService.java, src/main/resources/i18n/fr.json, src/main/resources/jsonschema/eval_createOrUpdateStructureOptionIsAverageSkills.json, src/main/resources/public/sass/global/_competences-specifics.scss, src/main/resources/public/sass/global/sniplets/_switch.scss, src/main/resources/public/template/behaviours/sniplet-structure-option-is-average-skills.html, src/main/resources/public/ts/behaviours.ts, src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts, src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts, src/main/resources/public/ts/models/common/Graph.ts, src/main/resources/public/ts/models/teacher/Structure.ts, src/main/resources/public/ts/models/teacher/SuiviCompetenceClasse.ts, src/main/resources/public/ts/models/teacher/Utils.ts, src/main/resources/public/ts/parameter.ts, src/main/resources/public/ts/services/index.ts, src/main/resources/public/ts/services/structure-options.service.ts, src/main/resources/public/ts/sniplets/structure-option-is-average-skills.ts, src/main/resources/sql/037-addColumnStructureOptions.sql
onglet competence dans viescolaire, premier menu
ajout d'une snipplet pour choisir le clacul des items de compétences : moyenne -> true, max -> false (valeur par défaut)
L'application sera faite sur une une branche. Cette PR est liée à la PR [#49](https://github.com/OPEN-ENT-NG/vie-scolaire/pull/49) de viscolaire sur la branche MSV-73
[API Documentation](https://confluence.support-ent.fr/display/MN/%5BNotes%5D+structureOptions)
Dans viescolaire -> onglet Competences -> menu Niveau de maitrice et calcul du niveau la snipplet du choix du calcul du niveau des items de compétences
[EVAL-334](https://jira.support-ent.fr/browse/EVAL-334)
[MVS-73](https://jira.support-ent.fr/browse/MVS-73)
=> feat: EVAL-334 add snipplet to choose the caculation of skill items And apply choice to competence

src/main/resources/public/ts/sniplets/itemsCompetences.ts
Fixed competence not being created in empty connaissance in VieScolaire Competence snipplet if no competences were previously there in a connaissance.
VieScolaire -> Competences -> Items de competence -> Try to create a competence on an empty connaissance, it should work.
[EVAL-390](https://jira.support-ent.fr/browse/EVAL-390)
=> fix(CreationCompetence) : EVAL-390 Fixed competence not being created in empty connaissance.

src/main/java/fr/openent/competences/controllers/ExportPDFController.java
EVAL-391 Fixed student marks PDF having a 2 decimals average instead of 1 decimal average like everything else.
Competences -> Suivi Eleve -> Suivi des notes -> Faire un export et vérifier que les moyennes de matières aient bien une seule décimale.
[EVAL-391](https://jira.support-ent.fr/browse/EVAL-391)
=> fix(ExportPDF) : EVAL-391 Fixed student marks PDF having a 2 decimals average

src/main/resources/public/ts/controllers/eval_parent_ctl.ts
Fixed getting an infinite load as a parent with 2 children in different periods category (such as one in semester class and one in trimester class) when switching which child to view.
Get a parent with 2 children, one with a class in semester, the other in trimester. Login and try to switch which children to view. It should now work.
[EVAL-411](https://jira.support-ent.fr/browse/EVAL-411)
=> fix(parents) : EVAL-411 Fixed infinite load as a 2 children parent.

src/main/resources/public/template/pdf/bulletin.pdf.xhtml
Fixed bulletins columns being shifted when not having subtopics.
Generate a bulletin without subtopics and check if the columns are right.
[EVAL-407](https://jira.support-ent.fr/browse/EVAL-407)
=> fix(bulletins) : EVAL-407 Fixed bulletins columns being shifted when not having subtopics.

src/main/resources/public/template/parent_enfant/releve/releve_notes.html
When hovering over the grades, the name of the assessment that gives that grade is displayed (as it is in the student view).
Connect with an account (not sudent) and in "Compétences" go to "Suivi Elève" --> "Suivi des notes" and move your cursor over the grades.
[EVAL-175](https://jira.support-ent.fr/browse/EVAL-175)
=> feat(titleAssessments): #EVAL-175 adding title of the assessments for all users

src/main/resources/public/template/parent_enfant/releve/releve_notes.html, src/main/resources/public/ts/models/parent_eleve/Matiere.ts, src/main/resources/public/ts/utils/functions/average.ts
Sur la page "Suivi élève", sur l'onglet "Suivi des notes", résolution d'un bug qui ne prenait pas en compte la surcharge de la moyenne lorsque qu'il y a la présence de sous matières
- Aller Relevé périodique d'une matière comportant des sous-matières (exemple récurent: anglais) pour n'importe quelle classe
- Surcharger la moyenne final d'un élève
- Se rendre sur le "Suivi des notes" de l'élève précédemment choisi
- observer que pour la moyenne finale, la surcharge est prise en compte.
- vérifier que pour une matière sans sous matière la moyenne finale et toujours pris en compte
[Jira - EVAL-447](https://jira.support-ent.fr/browse/EVAL-447)
=> fix(average) #EVAL-447 show override average even if subject got sub subjects

src/main/java/fr/openent/competences/controllers/ElementBilanPeriodiqueController.java, src/main/java/fr/openent/competences/controllers/StructureOptionsController.java, src/main/java/fr/openent/competences/security/AccessStructureAdminTeacherFilter.java, src/main/java/fr/openent/competences/security/AccessStructureAndAdminOrTeacherCourseFilter.java, src/main/java/fr/openent/competences/security/AdministratorRight.java, src/main/resources/public/ts/services/structure-options.service.ts, src/test/java/fr/openent/competences/security/AccessStructureAdminTeacherFilterTest.java, src/test/java/fr/openent/competences/security/AccessStructureAndAdminOrTeacherCourseFilterTest.java
After tests made up on NG2 dev-security branch, i had to modify AccessStructureAndAdminOrTeacherCourseFilter to remove checkouts on teacher's classroom.
Moreover, i had to debug the route post /structure/options/isSkillAverage because no structureId was passed in the front API route despite the fact that there is a checkout on the structure in the resource filter.
In "viescolaire", competences thumnail and "Niveau de maitrise et calcul du niveau", click on the switch button to ensure you have the rights to compute skill levels.
[#EVAL-489](https://jira.support-ent.fr/browse/EVAL-489)
=> Fix(security): #EVAL-489 modify AccessStructureAndAdminOrTeacherCourseFilter and add structure id in front API post /structure/options/isSkillAverage 

src/main/java/fr/openent/competences/Competences.java, src/main/java/fr/openent/competences/controllers/ModaliteController.java, src/main/java/fr/openent/competences/security/AccessIfMyStructure.java, src/main/java/fr/openent/competences/security/AccessViscoParamServiceStructure.java, src/main/java/fr/openent/competences/security/utils/WorkflowActions.java, src/main/resources/public/ts/sniplets/paramServices.ts, src/test/java/fr/openent/competences/security/AccessViscoParamServiceStructureTest.java
- For the route @Get("/modalites") : add query param idEtablissement to check structure within the resourceFilter AccessViscoParamServiceStructure.class.
This filter checks whether the user has the right structure and whether he has the workflow right : viescolaire.paramServices .
- Unit tests AccessViscoParamServiceStructureTest
- Tests with front file paramServices via browser to check whether the structure id is passed with query param.
- To check the route, go to viescolaire, competences thumbnail and then, just click on "modalités de services" in the left menu.
[#EVAL-444](https://jira.support-ent.fr/browse/EVAL-444)
=> fix(security): #EVAL-444 improve api's route security on ModaliteController

gradle.properties, src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/ExportPDFController.java, src/main/java/fr/openent/competences/service/DevoirService.java, src/main/java/fr/openent/competences/service/ExportService.java, src/main/java/fr/openent/competences/service/NoteService.java, src/main/java/fr/openent/competences/service/UtilsService.java, src/main/java/fr/openent/competences/service/impl/DefaultCompetencesService.java, src/main/java/fr/openent/competences/service/impl/DefaultDevoirService.java, src/main/java/fr/openent/competences/service/impl/DefaultExportService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java, src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/enseignants/suivi_competences_classe/content.html, src/main/resources/public/template/pdf/releve-classe.pdf.xhtml, src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts, src/main/resources/public/ts/controllers/eval_teacher_ctl.ts, src/main/resources/public/ts/core/enum/print.enum.ts, src/main/resources/public/ts/models/teacher/SuiviCompetenceClasse.ts, src/main/resources/public/ts/models/teacher/Utils.ts
Adds the possibility to print skills results to Releve de notes in Suivi Class via a list letting you chose between skills, scores and both skills&scores.
Suivi classe -> Download button -> "Le relevé de notes des élèves de la classe" -> test "Notes" and "Notes et compétences"
[EVAL-228](https://jira.support-ent.fr/browse/EVAL-228)
=> feat(ExportClasse) : #EVAL-228 Adds the possibility to print skills results to Releve de notes in Suivi Class.

src/main/resources/public/template/pdf/releve-classe.pdf.xhtml
Dans le PDF du suivi de classe, utilisation de la couleur par défaut quand la couleur personnalisée n'est pas définie.
Ajustement de la case "Bilan des items" pour qu'elle prenne systématiquement toute la longueur.
- Sur le suivie d'une classe, télécharger le bilan des notes (notes + compétences) au format PDF.
- Vérifie les réparations.
[Jira - EVAL-498](https://jira.support-ent.fr/browse/EVAL-498)
=> fix(class-report) #EVAL-498 fix skills line to always take full width and default colors.

src/main/resources/public/ts/models/teacher/Structure.ts
Ajout du paramètre "synchronized.devoirs" requis dans la méthode sync du modèle Structure.ts permettant d'attendre que a récupération des devoirs soit bien faite avant de passer à la suites de l'initialisation des données relatives à la page d'accueil de competences.
Afin de reproduire le bug initialement observé en preprod, il à fallu entourer l'appel de l'enpoint de la récupération des devoirs d'un setTimeout, afin de simuler la lenteur de la récupération. Celà a permis de bien reproduire ce problème en local.
[Jira - EVAL-467](https://jira.support-ent.fr/browse/EVAL-467)
=> fix(evaluation): #EVAL-467 waiting evaluations synchronisation before ending init script.

src/main/resources/public/ts/models/teacher/Eleve.ts
filtre sur les devoirs envoyés au back pour le calcul de la moyenne de l'élève. Fix de la précédente PR https://github.com/OPEN-ENT-NG/competences/pull/234
relevé périodique au moins deux devoirs (type évaluation et 1 formative). Modifier la une note sur l'évation non formative, la moyenne de l'élève est recalculer seulement avec les notes des devoirs de type évaluation.
[EVAL-528](https://jira.support-ent.fr/browse/EVAL-528)
=> fix(periodicStatement) #fix EVAL-528 calculte student's average only with the evaluation type

src/main/java/fr/openent/competences/controllers/ExportPDFController.java
Désormais, sur la page du suivi de classe, la récupération des appréciations des professeurs  sur une période annuel (donc sans filtrer de période) fonctionne.
- En tant que personnel, aller sur la page "Suivi classe" => "Appréciations professeurs"
- filtrer avec un group et avec la période "année"
- la page ne génère plus une 500, et fonctionne.
[Jira - EVAL-531](https://jira.support-ent.fr/browse/EVAL-531)
=> fix(class tracking) EVAL-531 fix getting teachers appreciations annually.

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java, src/test/java/fr/openent/competences/service/impl/DefaultExportBulletinServiceTest.java
Lors de l'export de bulletin, lorsqu'un élève avait 3 responsables utilisant la même adresse, on générait une erreur dans le code.
Traite désormais le cas dans lequel il y plus de 2 responsable avec la même adresse pour un étudiant.
- Dans la console admin, s'assurer qu'un élève a au moins 3 responsables avec la même adresse.
- Retourner dans compétence , sur l'onglet Générer les bulletins.
- tester l'export d'un bulletin pour l'élève en question. -> c'est ok.
[Jira - EVAL-530](https://jira.support-ent.fr/browse/EVAL-530)
=> fix(report-export) EVAL-530 handle the case where more than two responsible use the same address

src/main/resources/public/template/enseignants/suivi_eleve/left_side.html
Regression dû à cette PR: https://github.com/OPEN-ENT-NG/competences/pull/249
Lors de la sélection d'un groupe dans le suivi d'élève, le nom des étudiants dans le select suivant n'était plus affiché.
Correction de ce cas.
- Dans le suivi d'élève
- Sélectionner un groupe (pas une classe)
- vérifier dans le select des élève qu'ils sont bien affichés.
[Jira - EVAL-565](https://jira.support-ent.fr/browse/EVAL-565)
=> fix(student tracking) EVAL-565 show student names in select when we retrieve them from groups

src/main/java/fr/openent/competences/service/impl/DefaultTransitionService.java
Désormais au calcul de la moyenne des compétences lors de la transition d'année, le calcul ne se plus par période, mais dans sa globalité.
- Créer le cas sur un élève dans lequel sur une même compétence:
- trimestre 2: Il obtient 2 notes à 3 
- trimestre 3: Il obtient 1 note à 2 
- Refaire le flow de transition
- après cette transition => vérifier que sa moyenne de compétence (dans la vue cycle) est de 3 (et non plus comme avant de 2).
[Jira - EVAL-567](https://jira.support-ent.fr/browse/EVAL-567)
=> fix(transition) #EVAL-567: calculate skill average in transition is no more by periods

src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java, src/test/java/fr/openent/competences/service/impl/DefaultUtilsServiceTest.java
get student via the profilGroup - Structure and not via the ADMINISTRATIVE_ATTACHMENT relationship betwwen it and the structure
Creat manual student. Linked a parent. Connect with this parent : the child must be there.
[EVAL-566](https://jira.support-ent.fr/browse/EVAL-566)
=> fix: #EVAL-566 get manual student

src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
Désormais sur une matière, si un coenseignant à été supprimé, il n'est plus affiché.
- Suivi élève -> suivi des notes export de pdf
- Ajouter dans un premier temps un coenseignant
- Il est affiché à l'export du PDF
- Supprimer ce coenseignant
- Il n'est plus affiché à l'export du PDF
[Jira - EVAL-428](https://jira.support-ent.fr/browse/EVAL-428)
=> fix(student-tracking) #EVAL-428: show substitute teacher in pdf export only if not deleted

src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java, src/main/resources/public/ts/utils/functions/average.ts
- Initialement une moyenne à 12.85 est arrondi à 12.8 (inférieur) alors que ce qui est souhaité ici, c'est arrondi à la moyenne supérieur 12.9.
- Même problème à l'export PDF.
- Avoir un élève ayant une moyenne non arrondit à 12.85 (par exemple. Un note à 13 et une autre à 12.7 sur une matière).
- Suivi élève -> SUIVI DES NOTES
- La moyenne pour la matière sélectionnée doit être à 12.85 (en suivant l'exemple précédent)
- Idem sur l'export PDF.
[Jira - EVAL-542](https://jira.support-ent.fr/browse/EVAL-542)
=> fix(student-tracking) #EVAL-542: round the average up to one decimal when necessary

src/main/resources/public/ts/models/common/DefaultCompetence.ts, src/main/resources/public/ts/models/common/DefaultEnseignement.ts
Initialement, quand on sur le Suivi classe, en mode Vue par enseignements, quand on allait sur une autre vue (POSITIONNEMENTS par exemple) et qu'on revenais sur SUIVI DES ITEMS, plus aucune données ne s'affichaient.
fix ce problème.
- Suivi classe -> SUIVI DES ITEMS -> Vue par enseignements
- Les données sont affichés
-  POSITIONNEMENTS -> SUIVI DES ITEMS
- Le données sont toujours affichés
[Jira - EVAL-501](https://jira.support-ent.fr/browse/EVAL-501)
=> fix(class-tracking) #EVAL-501: reload data when we go out and come back into the competences by teaching view.

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/controllers/LSUController.java
Initialement, l'export bloquait lorsque la description était vide => "". Un message nous afficher que la description ne matchait pas avec la regex (.|\n)[^\s](.|\n).
- Ajouter mon modifier un projet éducatif (viescolaire => competences) en lui donnant cette description => &lt;script&gt;alert("XSS");&lt;/script&gt;
La chaine de caractère n'étant pas compatible avec la regex, le script d'enregistrement va enregistrer une chaine de caractère vide => c'est ce qui provoquait initialement notre problème.
- tester l'export lsu (competences)
- ça fonctionne !
[Jira - EVAL-540](https://jira.support-ent.fr/browse/EVAL-540)
=> feat(LSU) #EVAL-540: export LSU now nullifies description when empty

src/main/resources/public/ts/models/eval_parent_mdl.ts, src/main/resources/public/ts/utils/functions/average.ts
Initialement, sur la vue étudiant, dans le relevé périodique, avec la période sélectionné "Année", aucune notes ne s'affichais (empty state).
Correction de ce problème.
- se connecter en tant qu'étudiant
- Aller sur le relevé périodique
- filtrer par année
- les notes / moyennes s'affiches.
[Jira - EVAL-569](https://jira.support-ent.fr/browse/EVAL-569)
=> feat(student-view) #EVAL-569: fix showing scores in year view from periodic statement in student account.

src/main/java/fr/openent/competences/constants/Field.java, src/main/java/fr/openent/competences/service/impl/DefaultBilanPerioqueService.java, src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
This pull request introduces several enhancements and refactoring to the handling of subject averages and class-level calculations in the competences service. The main changes include the addition of new field constants, improvements to the calculation and transformation logic for subject and class averages, and code cleanup for consistency. These updates aim to provide more accurate and flexible handling of averages, especially for cases involving special statuses (such as "EA" and "NN") and third-class level students.
* Added new constants to `Field.java` for more granular handling of averages and status fields, such as `NULL`, `NULLFINALE`, `MOYENNEFINALE`, `MOYENNESFINALE`, and `MOYENNESCLASSE`. This improves clarity and prevents hardcoded string usage throughout the codebase. …
=> feat: #EVAL-664 update average api to add final status
